import { useEffect, useState } from 'react'
import { ArrowRight, Bell, CheckCircle2, Clock3, MapPin, Menu, Moon, MoveRight, ShieldCheck, Sparkles, Sun, Users, X } from 'lucide-react'
import { Link, NavLink, Route, Routes } from 'react-router-dom'
import { Button, Card, ErrorState, Modal, Toast } from './components'
import { QueueProvider } from './QueueContext.jsx'
import { useQueue } from './useQueue'
import { AdminPage, HistoryPage, JoinPage, LocationsPage, NotificationsPage, QueuePage, ReceiptPage, ServicesPage, SettingsPage, VoiceButton, VoiceModal } from './pages'
import './App.css'

const navItems = [{ label: 'Overview', to: '/' }, { label: 'Services', to: '/services' }, { label: 'Locations', to: '/locations' }, { label: 'My queue', to: '/queue' }]
function Navbar({ theme, onThemeToggle }) { const [menuOpen, setMenuOpen] = useState(false); const { currentQueue } = useQueue(); return <header className="navbar"><div className="container nav-inner"><Link className="brand" to="/"><span className="brand-mark"><MoveRight size={20} /></span><span>Queue<span className="brand-accent">Less</span></span></Link><nav className={menuOpen ? 'nav-links nav-links-open' : 'nav-links'} aria-label="Primary navigation">{navItems.map((item) => <NavLink key={item.to} to={item.to} onClick={() => setMenuOpen(false)} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>{item.label}{item.to === '/queue' && currentQueue ? <span className="nav-dot" /> : null}</NavLink>)}<Link className="nav-link nav-admin" to="/admin" onClick={() => setMenuOpen(false)}>Admin demo <ArrowRight size={15} /></Link></nav><div className="nav-actions"><Link className="icon-button" to="/notifications" aria-label="Notifications"><Bell size={18} /></Link><button className="icon-button" aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`} onClick={onThemeToggle}>{theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}</button><button className="menu-toggle icon-button" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div></header> }
function Footer() { return <footer className="footer"><div className="container footer-inner"><div><Link className="brand" to="/"><span className="brand-mark"><MoveRight size={20} /></span><span>Queue<span className="brand-accent">Less</span></span></Link><p className="footer-copy">Your time belongs to you.</p></div><div className="footer-links"><Link to="/services">Services</Link><Link to="/locations">Locations</Link><Link to="/history">History</Link><Link to="/settings">Settings</Link></div><p className="footer-meta">Â© 2026 QueueLess Â· Frontend demo</p></div></footer> }
function Overview() { const [showModal, setShowModal] = useState(false); const [voice, setVoice] = useState(false); const [toast, setToast] = useState(''); return <><main><section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Smart queue management</div><h1>Skip the line.<br /><em>Keep your time.</em></h1><p className="hero-lede">QueueLess lets you join queues remotely, track your place in real time, and arrive when it is actually your turn.</p><div className="hero-actions"><Button icon={ArrowRight} onClick={() => setShowModal(true)}>Join a queue</Button><Link className="button button-secondary" to="/services">Explore services <ArrowRight size={17} /></Link></div><div className="trust-row"><div className="avatar-stack"><span>AS</span><span>RK</span><span>JM</span></div><span>Trusted by 12,000+ people this month</span></div></div><QueuePreview /></div></section><section className="stats-band"><div className="container stats-grid"><Stat value="4.8k" label="People served today" icon={Users} /><Stat value="12 min" label="Average wait saved" icon={Clock3} /><Stat value="98.6%" label="On-time service" icon={CheckCircle2} /><Stat value="24/7" label="Digital access" icon={ShieldCheck} /></div></section><section className="section section-tint"><div className="container"><SectionIntro eyebrow="How it works" title="A simple flow anyone can understand." copy="QueueLess turns a confusing line into a clear, visual journey that feels easy to follow." /><div className="visual-flow"><VisualStep icon={MapPin} title="1. Choose" detail="Pick the service you need and see the expected wait." accent="service" miniLabel="CityCare" miniValue="18 min" /><div className="flow-arrow" aria-hidden="true"><ArrowRight size={20} /></div><VisualStep icon={Bell} title="2. Get a token" detail="A digital ticket is created instantly for you." accent="token" miniLabel="Your token" miniValue="A-127" /><div className="flow-arrow" aria-hidden="true"><ArrowRight size={20} /></div><VisualStep icon={CheckCircle2} title="3. Track live" detail="Stay updated until it is your turn to be helped." accent="track" miniLabel="People ahead" miniValue="3" /></div></div></section>
<section className="section container"><SectionIntro eyebrow="A calmer way to wait" title="Your day, uninterrupted." copy="QueueLess brings the whole waiting experience into one clear, quiet space." /><div className="feature-grid"><Feature number="01" title="Find your service" copy="Browse trusted service centers and see live queue conditions before you leave." /><Feature number="02" title="Join from anywhere" copy="Choose your service, get a digital token, and keep moving with your day." /><Feature number="03" title="Arrive at the right time" copy="Live updates tell you when your turn is close, so you never have to guess." /></div></section><section className="section section-tint"><div className="container split-feature"><div><div className="eyebrow">Built for real life</div><h2>Less waiting.<br /><em>More living.</em></h2><p>Whether it is a clinic, campus, bank, or public office, QueueLess gives every visitor a more predictable and respectful experience.</p><Link className="text-link" to="/locations">See available locations <ArrowRight size={16} /></Link></div><Card className="quote-card"><Sparkles className="quote-spark" size={20} /><p>â€œI joined the queue from the cafÃ© and arrived just as my number was called. It gave me my afternoon back.â€</p><div className="quote-author"><span className="author-avatar">NR</span><div><strong>Nisha Rao</strong><span>CityCare visitor</span></div></div></Card></div></section><section className="cta-section container"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">Ready when you are</div><h2>Turn waiting time<br />into <em>your time.</em></h2></div><Button variant="light" icon={ArrowRight} onClick={() => setShowModal(true)}>Find a service</Button></div></section></main><VoiceButton onClick={() => setVoice(true)} /><Modal open={showModal} title="Join a queue" onClose={() => setShowModal(false)}><p className="modal-copy">Choose a service to get started.</p><Link className="button button-primary modal-action" to="/services" onClick={() => setShowModal(false)}>Browse services <ArrowRight size={17} /></Link></Modal><VoiceModal open={voice} onClose={() => setVoice(false)} /><Toast message={toast} onClose={() => setToast('')} /></> }
function QueuePreview() { return <div className="preview-wrap"><div className="preview-orbit orbit-one" /><div className="preview-orbit orbit-two" /><Card className="queue-preview"><div className="preview-top"><span className="live-label"><span /> Live queue</span><span className="preview-time">Updated just now</span></div><div className="preview-main"><span className="preview-label">Your position</span><strong>06</strong><span className="preview-muted">people ahead of you</span></div><div className="progress-track"><span style={{ width: '68%' }} /></div><div className="preview-details"><div><span>Estimated wait</span><strong>18 min</strong></div><div><span>Now serving</span><strong>A-121</strong></div><div><span>Counter</span><strong>02</strong></div></div><div className="preview-alert"><Bell size={16} /><span>Your turn is coming soon</span></div></Card></div> }
function Stat({ value, label, icon: Icon }) { return <div className="stat"><Icon size={20} /><div><strong>{value}</strong><span>{label}</span></div></div> }
function VisualStep({ icon: Icon, title, detail, accent, miniLabel, miniValue }) {
  return <div className={`visual-step visual-${accent}`}>
    <div className="visual-icon"><Icon size={20} /></div>
    <h3>{title}</h3>
    <p>{detail}</p>
    <div className="mini-visual">
      <span>{miniLabel}</span>
      <strong>{miniValue}</strong>
    </div>
  </div>
}
function SectionIntro({ eyebrow, title, copy }) { return <div className="section-intro"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{copy}</p></div> }
function Feature({ number, title, copy }) { return <Card className="feature-card"><span className="feature-number">{number}</span><h3>{title}</h3><p>{copy}</p><ArrowRight className="feature-arrow" size={18} /></Card> }
function NotFound() { return <main className="placeholder-page container"><ErrorState title="This page is not available" description="The route you entered does not exist in this demo." /><Link className="button button-primary" to="/">Return home <ArrowRight size={17} /></Link></main> }
function AppContent() {
  const { settings } = useQueue();
  const [theme, setTheme] = useState(() => localStorage.getItem('queueless-theme') || 'light');
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('queueless-theme', theme) }, [theme]);
  useEffect(() => {
    try {
      const pending = JSON.parse(localStorage.getItem('queueless-pending-notification') || 'null');
      if (!pending) return;
      if (settings.browser && 'Notification' in window && Notification.permission === 'granted') {
        new Notification(pending.title, {
          body: pending.body,
          tag: pending.tag || 'queueless-resume',
        });
      }
      localStorage.removeItem('queueless-pending-notification');
    } catch {
      localStorage.removeItem('queueless-pending-notification');
    }
  }, [settings.browser]);

  return <div className="app-shell"><Navbar theme={theme} onThemeToggle={() => setTheme(theme === 'light' ? 'dark' : 'light')} /><Routes><Route path="/" element={<Overview />} /><Route path="/services" element={<ServicesPage />} /><Route path="/locations" element={<LocationsPage />} /><Route path="/join" element={<JoinPage />} /><Route path="/queue" element={<QueuePage />} /><Route path="/notifications" element={<NotificationsPage />} /><Route path="/history" element={<HistoryPage />} /><Route path="/receipt/:id" element={<ReceiptPage />} /><Route path="/settings" element={<SettingsPage />} /><Route path="/about" element={<PlaceholderPage />} /><Route path="/admin" element={<AdminPage />} /><Route path="/admin/queue" element={<AdminPage section="queue" />} /><Route path="/admin/counters" element={<AdminPage section="counters" />} /><Route path="/admin/services" element={<AdminPage section="services" />} /><Route path="/admin/analytics" element={<AdminPage section="analytics" />} /><Route path="*" element={<NotFound />} /></Routes><Footer /></div> }

function PlaceholderPage() { return <main className="placeholder-page container"><div className="placeholder-icon"><Sparkles size={26} /></div><div className="eyebrow">QueueLess</div><h1>A better way to wait.</h1><p>QueueLess is a digital queue management platform designed around people's time.</p><Link className="button button-primary" to="/services">Explore services <ArrowRight size={17} /></Link></main> }
function App() { return <QueueProvider><AppContent /></QueueProvider> }
export default App

